import { technique } from '../mitre.js';
import { e, makeScenario } from './shared.js';

export const groupAScenarios = [
  makeScenario({
    id: 'suspicious-rdp-login', title: 'Inicio RDP fuera de patrón', difficulty: 'Foundation', category: 'Lateral Movement', severity: 'high',
    description: 'Un acceso RDP de proveedor aparece fuera de su ventana habitual y precede a actividad interactiva.',
    briefing: 'Valida la sesión remota, el control de acceso y la actividad posterior sin asumir que toda conexión del proveedor es hostil.',
    businessContext: 'Un proveedor de operaciones dispone de RDP limitado al jump host durante ventanas de mantenimiento aprobadas.',
    host: 'ops-jump-02', user: 'ext.perez', sourceIp: '198.51.100.84', verdict: 'true-positive', noiseCount: 56,
    noiseSources: ['windows', 'auth', 'firewall', 'sysmon'], alerts: ['RDP desde geolocalización nueva', 'Sesión interactiva fuera de ventana'],
    techniques: [technique('T1021.001'), technique('T1078')],
    iocs: [{ type: 'ip', value: '198.51.100.84', context: 'Origen de la sesión RDP no aprobada' }],
    events: [
      e(18, 'firewall', 'rd-gw-01', 'ext.perez', '198.51.100.84', 'ALLOW-3389', 'connection_allowed', 'success', 'Inbound RDP session forwarded to ops-jump-02', { destination_port: 3389, geo: 'RO' }, '10.40.8.22'),
      e(19, 'windows', 'ops-jump-02', 'ext.perez', '198.51.100.84', '4625', 'login', 'failure', 'Failed remote interactive logon for ext.perez', { logon_type: 10, workstation: 'FREERDP' }),
      e(21, 'auth', 'rd-gw-01', 'ext.perez', '198.51.100.84', 'MFA-DENY', 'mfa_challenge', 'failure', 'First MFA challenge denied by registered user', { device_trust: false }),
      e(24, 'windows', 'ops-jump-02', 'ext.perez', '198.51.100.84', '4624', 'login', 'success', 'Remote interactive logon type 10 accepted', { logon_type: 10, authentication_package: 'Negotiate' }),
      e(27, 'sysmon', 'ops-jump-02', 'ext.perez', '10.40.8.22', '1', 'process_start', 'success', 'mstsc session spawned cmd.exe then whoami.exe', { parent: 'explorer.exe', process: 'cmd.exe' }),
      e(31, 'windows', 'ops-jump-02', 'ext.perez', '10.40.8.22', '4634', 'logout', 'success', 'Remote interactive session ended after seven minutes', { logon_type: 10 }),
    ],
    pivot: { prompt: '¿Qué tipo de logon confirma que fue una sesión RDP?', value: 'Logon Type 10', aliases: ['10', 'remote interactive'], evidenceTerms: ['logon_type', '10'] },
    scope: { prompt: '¿Qué gateway reenvió la sesión y registró el desafío MFA?', value: 'rd-gw-01', evidenceTerms: ['rd-gw-01', 'MFA-DENY'] },
    explanation: 'El origen nuevo atraviesa el gateway, provoca un rechazo MFA y finalmente obtiene un logon tipo 10 fuera de ventana; la ejecución interactiva posterior elimina la hipótesis de mero escaneo.',
    response: ['Aislar ops-jump-02 y cerrar la sesión RDP', 'Bloquear temporalmente el origen en rd-gw-01'],
    remediation: ['Rotar la cuenta del proveedor y revisar el segundo factor', 'Restringir RDP a dispositivos y ventanas autorizadas'],
    kql: ['eventCode:("4624" or "4625") and host:"ops-jump-02"', 'sourceIp:"198.51.100.84" and source:("firewall" or "auth")'],
    spl: ['index=soc host=ops-jump-02 eventCode IN (4624,4625) | sort timestamp', 'index=soc sourceIp=198.51.100.84 | stats values(action) by host user'],
    sigmaSelection: 'eventCode: 4624\n    details.logon_type: 10',
  }),
  makeScenario({
    id: 'account-lockout', title: 'Bloqueo repetido de cuenta de RR. HH.', difficulty: 'Foundation', category: 'Credential Access', severity: 'medium',
    description: 'Una cuenta se bloquea tres veces mientras la usuaria afirma no estar iniciando sesión.',
    briefing: 'Determina qué equipo origina los fallos y si se trata de credenciales obsoletas o de un intento deliberado.',
    businessContext: 'La usuaria trabaja de forma híbrida y usa un portátil corporativo y un kiosco compartido para fichar.',
    host: 'kiosk-hr-02', user: 'ana.torres', sourceIp: '10.40.33.58', verdict: 'true-positive', noiseCount: 58,
    noiseSources: ['windows', 'auth', 'endpoint'], alerts: ['Tres bloqueos de cuenta en 40 minutos', 'Fallos NTLM desde dispositivo compartido'],
    techniques: [technique('T1110.001')], iocs: [{ type: 'ip', value: '10.40.33.58', context: 'Kiosco origen de la adivinación de contraseña' }],
    events: [
      e(14, 'windows', 'dc-02', 'ana.torres', '10.40.33.58', '4776', 'credential_validation', 'failure', 'NTLM credential validation failed from KIOSK-HR-02', { status: '0xC000006A' }),
      e(16, 'auth', 'dc-02', 'ana.torres', '10.40.33.58', 'LOGIN-BURST', 'login', 'failure', 'Eight password guesses observed with changing workstation process IDs', { attempts: 8 }),
      e(18, 'windows', 'dc-02', 'ana.torres', '10.40.33.58', '4740', 'account_lockout', 'success', 'User account ana.torres locked out; caller computer KIOSK-HR-02', { caller: 'KIOSK-HR-02' }),
      e(26, 'endpoint', 'kiosk-hr-02', 'local.service', '10.40.33.58', 'PROC-START', 'process_start', 'success', 'Unsigned helper kiosk-sync.exe accessed Windows credential APIs', { process: 'kiosk-sync.exe', signed: false }),
      e(31, 'windows', 'dc-02', 'ana.torres', '10.40.33.58', '4776', 'credential_validation', 'failure', 'Credential validation resumed after helpdesk unlock', { attempts: 5 }),
    ],
    pivot: { prompt: '¿Qué evento identifica el equipo que provoca el bloqueo?', value: '4740', evidenceTerms: ['4740', 'KIOSK-HR-02'] },
    scope: { prompt: '¿Qué proceso local vincula el dispositivo con los nuevos intentos?', value: 'kiosk-sync.exe', evidenceTerms: ['kiosk-sync.exe', 'PROC-START'] },
    explanation: 'El 4740 apunta al kiosco, pero los fallos reaparecen después del desbloqueo y coinciden con un helper sin firma que usa APIs de credenciales; no es un móvil con contraseña antigua.',
    response: ['Aislar kiosk-hr-02 y deshabilitar temporalmente kiosk-sync.exe', 'Mantener bloqueada la cuenta hasta completar el análisis'],
    remediation: ['Reimaginar el kiosco y retirar el helper no autorizado', 'Separar identidades de usuario de servicios del kiosco'],
    kql: ['user:"ana.torres" and eventCode:("4776" or "4740")', 'host:"kiosk-hr-02" and details.signed:false'],
    spl: ['index=soc user=ana.torres eventCode IN (4776,4740) | transaction user maxspan=45m', 'index=soc host=kiosk-hr-02 details.signed=false'],
    sigmaSelection: 'eventCode: 4740',
  }),
  makeScenario({
    id: 'web-directory-bruteforce', title: 'Enumeración de directorios web', difficulty: 'Foundation', category: 'Reconnaissance', severity: 'medium',
    description: 'El WAF observa una sucesión de respuestas 404 y 403 contra rutas poco habituales.',
    briefing: 'Diferencia un crawler normal de un escaneo por diccionario y confirma si alguna ruta sensible respondió.',
    businessContext: 'El portal de partners es público; los crawlers autorizados se identifican y respetan robots.txt.',
    host: 'portal-02', user: 'anonymous', sourceIp: '198.51.100.126', verdict: 'true-positive', noiseCount: 61,
    noiseSources: ['http', 'firewall', 'suricata', 'dns'], alerts: ['Ratio elevado de 404 por cliente', 'Acceso denegado a ruta administrativa'],
    techniques: [technique('T1595.003')], iocs: [{ type: 'ip', value: '198.51.100.126', context: 'Origen del escaneo distribuido en rutas' }],
    events: [
      e(12, 'http', 'portal-02', 'anonymous', '198.51.100.126', '404', 'web_request', 'failure', 'GET /old-admin returned 404', { user_agent: 'Mozilla/5.0', uri: '/old-admin' }),
      e(13, 'http', 'portal-02', 'anonymous', '198.51.100.126', '404', 'web_request', 'failure', 'GET /.git/config returned 404', { uri: '/.git/config' }),
      e(14, 'http', 'portal-02', 'anonymous', '198.51.100.126', '403', 'web_request', 'failure', 'GET /server-status returned 403', { uri: '/server-status' }),
      e(15, 'suricata', 'waf-01', 'anonymous', '198.51.100.126', 'SURICATA-2100365', 'web_scan', 'unknown', 'Multiple uncommon URI requests with stable client fingerprint', { distinct_paths: 47 }),
      e(17, 'firewall', 'portal-02', 'anonymous', '198.51.100.126', 'RATE-LIMIT', 'connection_blocked', 'success', 'HTTP client rate limited after 63 requests', { requests_per_minute: 63 }),
    ],
    pivot: { prompt: '¿Qué ruta sensible respondió 403 en lugar de 404?', value: '/server-status', evidenceTerms: ['/server-status', '403'] },
    scope: { prompt: '¿Cuántas rutas distintas resume la señal correlacionada?', value: '47', aliases: ['47 rutas', '47 paths'], evidenceTerms: ['47', 'SURICATA-2100365'] },
    explanation: 'La diversidad de rutas, el orden de diccionario, la ausencia de robots.txt y el fingerprint estable encajan con enumeración activa; no hubo acceso exitoso.',
    response: ['Bloquear temporalmente 198.51.100.126 en el WAF', 'Conservar access logs y fingerprint del cliente'],
    remediation: ['Retirar rutas y metadatos innecesarios', 'Ajustar rate limiting por diversidad de URI, no sólo volumen'],
    kql: ['host:"portal-02" and sourceIp:"198.51.100.126" and eventCode:("404" or "403")', 'action:"web_scan" or eventCode:"RATE-LIMIT"'],
    spl: ['index=soc host=portal-02 sourceIp=198.51.100.126 | stats dc(details.uri) as paths values(eventCode)', 'index=soc action=web_scan OR eventCode=RATE-LIMIT'],
    sigmaSelection: 'action: web_scan',
  }),
  makeScenario({
    id: 'suspicious-scheduled-task', title: 'Tarea programada fuera de estándar', difficulty: 'Foundation', category: 'Persistence', severity: 'high',
    description: 'Una tarea con nombre parecido al software corporativo ejecuta un script desde el perfil público.',
    briefing: 'Reconstruye quién creó la tarea, qué proceso la originó y qué ejecuta realmente.',
    businessContext: 'Ingeniería usa tareas firmadas desplegadas por GPO; las estaciones no deben crear tareas desde perfiles de usuario.',
    host: 'eng-wks-08', user: 'support.local', sourceIp: '10.40.36.48', verdict: 'true-positive', noiseCount: 60,
    noiseSources: ['windows', 'sysmon', 'endpoint'], alerts: ['Evento 4698 fuera de ventana GPO', 'Script desde C:\\Users\\Public'],
    techniques: [technique('T1053.005')], iocs: [{ type: 'path', value: 'C:\\Users\\Public\\telemetry.vbs', context: 'Script ejecutado por la tarea' }],
    events: [
      e(11, 'sysmon', 'eng-wks-08', 'support.local', '10.40.36.48', '1', 'process_start', 'success', 'wscript.exe launched from an interactive support session', { parent: 'explorer.exe', process: 'wscript.exe' }),
      e(13, 'windows', 'eng-wks-08', 'support.local', '10.40.36.48', '4698', 'scheduled_task_create', 'success', 'Scheduled task Vendor Telemetry Check created', { task_name: 'Vendor Telemetry Check', command: 'C:\\Users\\Public\\telemetry.vbs' }),
      e(14, 'endpoint', 'eng-wks-08', 'support.local', '10.40.36.48', 'FILE-NEW', 'file_create', 'success', 'C:\\Users\\Public\\telemetry.vbs created by wscript.exe', { hash: '7d31c5a9-synthetic' }),
      e(18, 'windows', 'eng-wks-08', 'SYSTEM', '10.40.36.48', 'TASK-START', 'scheduled_task_start', 'success', 'Vendor Telemetry Check started as SYSTEM', { task_name: 'Vendor Telemetry Check' }),
      e(18.2, 'sysmon', 'eng-wks-08', 'SYSTEM', '10.40.36.48', '1', 'process_start', 'success', 'taskeng.exe spawned wscript.exe with telemetry.vbs', { parent: 'taskeng.exe', process: 'wscript.exe' }),
    ],
    pivot: { prompt: '¿Qué proceso creó y ejecutó el script de la tarea?', value: 'wscript.exe', evidenceTerms: ['wscript.exe'] },
    scope: { prompt: '¿Qué script ejecuta la tarea con contexto SYSTEM?', value: 'telemetry.vbs', aliases: ['C:\\Users\\Public\\telemetry.vbs'], evidenceTerms: ['telemetry.vbs', 'TASK-START'] },
    explanation: 'La tarea no procede de GPO, referencia un script nuevo en Public y se ejecuta como SYSTEM; el nombre similar al proveedor es camuflaje.',
    response: ['Aislar eng-wks-08 y deshabilitar la tarea', 'Preservar telemetry.vbs antes de retirarlo'],
    remediation: ['Rotar las credenciales de support.local', 'Restringir creación de tareas y ejecución de scripts mediante política'],
    kql: ['host:"eng-wks-08" and eventCode:("4698" or "TASK-START")', 'details.command:"C:\\\\Users\\\\Public\\\\telemetry.vbs"'],
    spl: ['index=soc host=eng-wks-08 eventCode IN (4698,TASK-START) | sort timestamp', 'index=soc details.command="*telemetry.vbs"'],
    sigmaSelection: "eventCode: 4698\n    details.command|contains: 'C:\\Users\\Public\\'",
  }),
  makeScenario({
    id: 'browser-download', title: 'Descarga sospechosa desde navegador', difficulty: 'Foundation', category: 'Execution', severity: 'high',
    description: 'Una descarga de navegador termina montada y ejecutada, aunque el dominio imita un CDN utilizado por marketing.',
    briefing: 'Correlaciona navegación, escritura, montaje y árbol de procesos para decidir si el archivo llegó a ejecutarse.',
    businessContext: 'Marketing descarga habitualmente recursos gráficos, pero el software sólo se instala desde el portal corporativo.',
    host: 'marketing-wks-11', user: 'sofia.navas', sourceIp: '10.40.38.71', verdict: 'true-positive', noiseCount: 63,
    noiseSources: ['dns', 'http', 'endpoint', 'sysmon'], alerts: ['ISO descargada desde dominio nuevo', 'Proceso de sistema hijo de imagen montada'],
    techniques: [technique('T1204.002'), technique('T1105')],
    iocs: [{ type: 'domain', value: 'assets-cdn-files.example', context: 'Dominio que sirvió la imagen' }, { type: 'hash', value: 'b4c80d22-synthetic', context: 'Hash del archivo ISO' }],
    events: [
      e(9, 'dns', 'marketing-wks-11', 'sofia.navas', '10.40.38.71', 'DNS-Q', 'dns_query', 'success', 'Query A assets-cdn-files.example', { domain: 'assets-cdn-files.example' }),
      e(10, 'http', 'proxy-02', 'sofia.navas', '10.40.38.71', '200', 'download', 'success', 'GET https://assets-cdn-files.example/brand-pack.iso', { bytes: 12845056, mime: 'application/octet-stream' }),
      e(11, 'endpoint', 'marketing-wks-11', 'sofia.navas', '10.40.38.71', 'FILE-NEW', 'file_create', 'success', 'msedge.exe wrote brand-pack.iso to Downloads', { hash: 'b4c80d22-synthetic', process: 'msedge.exe' }),
      e(15, 'windows', 'marketing-wks-11', 'sofia.navas', '10.40.38.71', 'VOLUME-MOUNT', 'volume_mount', 'success', 'Disk image brand-pack.iso mounted as drive E:', { drive: 'E:' }),
      e(16, 'sysmon', 'marketing-wks-11', 'sofia.navas', '10.40.38.71', '1', 'process_start', 'success', 'explorer.exe spawned E:\\preview.exe which launched rundll32.exe', { parent: 'preview.exe', process: 'rundll32.exe' }),
      e(18, 'endpoint', 'marketing-wks-11', 'sofia.navas', '10.40.38.71', 'QUARANTINE', 'file_quarantine', 'success', 'Unsigned preview.exe quarantined after child-process policy match', { signed: false }),
    ],
    pivot: { prompt: '¿Qué proceso hijo demuestra que la descarga se ejecutó?', value: 'rundll32.exe', evidenceTerms: ['rundll32.exe', 'preview.exe'] },
    scope: { prompt: '¿Qué imagen de disco conecta descarga, montaje y ejecución?', value: 'brand-pack.iso', evidenceTerms: ['brand-pack.iso', 'VOLUME-MOUNT'] },
    explanation: 'DNS y proxy sólo prueban descarga; el montaje de la ISO, preview.exe y su hijo rundll32 demuestran ejecución por el usuario.',
    response: ['Aislar marketing-wks-11 y conservar la ISO', 'Bloquear assets-cdn-files.example y el hash'],
    remediation: ['Revisar credenciales y sesiones de sofia.navas', 'Bloquear montaje de imágenes descargadas y reforzar filtrado web'],
    kql: ['host:"marketing-wks-11" and action:("volume_mount" or "process_start")', 'details.hash:"b4c80d22-synthetic" or details.domain:"assets-cdn-files.example"'],
    spl: ['index=soc host=marketing-wks-11 action IN (volume_mount,process_start) | sort timestamp', 'index=soc details.hash=b4c80d22-synthetic OR details.domain=assets-cdn-files.example'],
    sigmaSelection: 'action: volume_mount\n    message|contains: ".iso"',
  }),
];
