import { technique } from '../mitre.js';
import { e, makeScenario } from './shared.js';

export const groupCScenarios = [
  makeScenario({
    id: 'initial-access-execution-persistence', title: 'Acceso inicial, shell y persistencia cron', difficulty: 'Advanced', category: 'Multi-stage Intrusion', severity: 'critical',
    description: 'Una API pública recibe una petición anómala, ejecuta una shell y crea persistencia periódica.',
    briefing: 'Reconstruye la cadena desde HTTP hasta cron, separando health checks, despliegues y comandos del proceso web.',
    businessContext: 'La API de pedidos está expuesta detrás de WAF; los despliegues llegan exclusivamente desde runner-prod-01.',
    host: 'api-orders-01', user: 'www-api', sourceIp: '192.0.2.143', verdict: 'true-positive', noiseCount: 154,
    noiseSources: ['http', 'suricata', 'linux', 'network', 'dns', 'firewall'], alerts: ['Payload de expresión en endpoint público', 'Shell hija del proceso API', 'Nuevo cron de usuario web'],
    techniques: [technique('T1190'), technique('T1059.004'), technique('T1053.003')],
    iocs: [{ type: 'ip', value: '192.0.2.143', context: 'Origen del exploit' }, { type: 'path', value: '/var/spool/cron/www-api', context: 'Persistencia creada' }, { type: 'domain', value: 'pkg-mirror-edge.example', context: 'Origen de la segunda fase sintética' }],
    events: [
      e(32, 'http', 'api-orders-01', 'anonymous', '192.0.2.143', '500', 'web_request', 'failure', 'POST /api/v2/render produced template expression exception', { uri: '/api/v2/render', body_size: 418 }),
      e(33, 'suricata', 'waf-02', 'anonymous', '192.0.2.143', 'SURICATA-2100401', 'exploit_attempt', 'unknown', 'Expression language metacharacters observed in request body', { flow_id: 'flow-a812' }),
      e(34, 'linux', 'api-orders-01', 'www-api', '192.0.2.143', 'execve', 'process_start', 'success', 'java spawned /bin/sh -c id; uname -a', { parent: 'java', process: '/bin/sh' }),
      e(36, 'dns', 'api-orders-01', 'www-api', '10.40.16.41', 'DNS-Q', 'dns_query', 'success', 'Query A pkg-mirror-edge.example from curl process', { domain: 'pkg-mirror-edge.example' }),
      e(37, 'network', 'api-orders-01', 'www-api', '10.40.16.41', 'TLS', 'download', 'success', 'curl retrieved 18412 bytes from pkg-mirror-edge.example', { process: 'curl', bytes: 18412 }),
      e(41, 'linux', 'api-orders-01', 'www-api', '10.40.16.41', 'FILE-WRITE', 'file_create', 'success', '/var/spool/cron/www-api modified outside deployment', { path: '/var/spool/cron/www-api' }),
      e(42, 'linux', 'api-orders-01', 'www-api', '10.40.16.41', 'CRON', 'scheduled_job', 'success', 'Cron entry runs /var/tmp/.sys-check every 12 minutes', { command: '/var/tmp/.sys-check', interval: 12 }),
      e(53, 'firewall', 'egress-fw-02', 'www-api', '10.40.16.41', 'DENY', 'connection_blocked', 'success', 'Unexpected outbound connection from API subnet blocked', { destination_port: 8443 }),
      e(68, 'linux', 'api-orders-01', 'deploy.prod', '10.40.5.61', 'DEPLOY', 'application_deploy', 'success', 'Approved release 2026.09.18 deployed from runner-prod-01', { ticket: 'REL-9914' }),
    ],
    pivot: { prompt: '¿Qué proceso padre conecta el exploit web con la shell?', value: 'java', evidenceTerms: ['java', '/bin/sh'] },
    scope: { prompt: '¿Qué mecanismo mantiene acceso tras el exploit?', value: '/var/spool/cron/www-api', aliases: ['cron', '/var/tmp/.sys-check'], evidenceTerms: ['/var/spool/cron/www-api', 'CRON'] },
    explanation: 'El flow-id une WAF y HTTP; java crea /bin/sh, curl recupera segunda fase y se modifica el cron. El despliegue posterior tiene origen y ticket aprobados, por lo que es ruido legítimo.',
    response: ['Retirar api-orders-01 del balanceador y aislarlo', 'Bloquear el origen y pkg-mirror-edge.example'],
    remediation: ['Recrear el servidor desde imagen limpia y rotar secretos de API', 'Corregir la expresión vulnerable y restringir egress del proceso web'],
    kql: ['host:"api-orders-01" and action:("web_request" or "process_start" or "file_create" or "scheduled_job")', 'sourceIp:"192.0.2.143" or details.domain:"pkg-mirror-edge.example"'],
    spl: ['index=soc host=api-orders-01 | transaction host maxspan=30m', 'index=soc sourceIp=192.0.2.143 OR details.domain=pkg-mirror-edge.example'],
    sigmaSelection: 'action: process_start\n    details.parent: java\n    details.process: /bin/sh',
  }),
  makeScenario({
    id: 'spray-compromise-recon', title: 'Password spray, VPN y reconocimiento interno', difficulty: 'Advanced', category: 'Credential Access → Discovery', severity: 'critical',
    description: 'Un spray cloud obtiene una cuenta, abre VPN y enumera identidades y controladores internos.',
    briefing: 'Correlaciona la identidad a través de cloud auth, asignación VPN, Kerberos, procesos y LDAP.',
    businessContext: 'El acceso remoto requiere MFA y dispositivos gestionados; la usuaria no pertenece al equipo de infraestructura.',
    host: 'vpn-gw-01', user: 'irene.martin', sourceIp: '198.51.100.202', verdict: 'true-positive', noiseCount: 164,
    noiseSources: ['cloud', 'auth', 'network', 'windows', 'sysmon', 'firewall'], alerts: ['Fallos horizontales de autenticación', 'VPN sin postura de dispositivo', 'Consultas LDAP de reconocimiento'],
    techniques: [technique('T1110.003'), technique('T1078'), technique('T1087.002')],
    iocs: [{ type: 'ip', value: '198.51.100.202', context: 'Origen del spray y VPN' }, { type: 'user', value: 'irene.martin', context: 'Cuenta comprometida' }],
    events: [
      e(28, 'cloud', 'entra-id', 'sales.group', '198.51.100.202', 'AADSTS50126', 'cloud_login', 'failure', 'Single password attempted across twelve sales identities', { distinct_users: 12 }),
      e(34, 'cloud', 'entra-id', 'irene.martin', '198.51.100.202', 'AAD-SUCCESS', 'cloud_login', 'success', 'Password accepted for irene.martin; legacy MFA claim reused', { device_id: 'unregistered' }),
      e(38, 'auth', 'vpn-gw-01', 'irene.martin', '198.51.100.202', 'VPN-200', 'vpn_login', 'success', 'VPN session established without compliant device posture', { assigned_ip: '10.99.8.44' }),
      e(42, 'firewall', 'core-fw-01', 'irene.martin', '10.99.8.44', 'ALLOW-LDAP', 'connection_allowed', 'success', 'VPN client connected to dc-02 LDAP 389', { destination_port: 389 }, '10.40.10.12'),
      e(43, 'windows', 'dc-02', 'irene.martin', '10.99.8.44', '4662', 'directory_query', 'success', 'LDAP query enumerated person and computer objects', { object_classes: 'person,computer', results: 387 }),
      e(45, 'sysmon', 'vpn-session-44', 'irene.martin', '10.99.8.44', '1', 'process_start', 'success', 'cmd.exe spawned nltest.exe /dclist:corp.example', { parent: 'cmd.exe', process: 'nltest.exe' }),
      e(47, 'windows', 'dc-02', 'irene.martin', '10.99.8.44', '4769', 'ticket_request', 'success', 'Service tickets requested for CIFS on four servers', { service_count: 4 }),
      e(59, 'cloud', 'entra-id', 'irene.martin', '10.40.21.18', 'AAD-SUCCESS', 'cloud_login', 'success', 'Normal managed laptop sign-in with phishing-resistant MFA', { device_id: 'corp-8821', mfa: true }),
    ],
    pivot: { prompt: '¿Qué dirección VPN enlaza el acceso cloud con LDAP interno?', value: '10.99.8.44', evidenceTerms: ['10.99.8.44', 'assigned_ip'] },
    scope: { prompt: '¿Qué controlador recibió la enumeración LDAP?', value: 'dc-02', evidenceTerms: ['dc-02', '4662'] },
    explanation: 'El mismo origen logra la cuenta tras el spray y obtiene 10.99.8.44. Esa IP consulta LDAP, ejecuta nltest y solicita tickets CIFS; el acceso posterior del portátil corporativo es legítimo pero no invalida el compromiso.',
    response: ['Desconectar la VPN y revocar sesiones de irene.martin', 'Bloquear 198.51.100.202 y la IP VPN interna'],
    remediation: ['Restablecer la cuenta y exigir MFA resistente a phishing', 'Impedir VPN sin postura y limitar LDAP desde el pool remoto'],
    kql: ['sourceIp:"198.51.100.202" and action:("cloud_login" or "vpn_login")', 'sourceIp:"10.99.8.44" and action:("connection_allowed" or "directory_query" or "ticket_request")'],
    spl: ['index=soc sourceIp=198.51.100.202 | stats values(action) by user', 'index=soc sourceIp=10.99.8.44 | transaction user maxspan=20m'],
    sigmaSelection: 'action: directory_query\n    details.results|gte: 300',
  }),
  makeScenario({
    id: 'web-exploit-webshell-command', title: 'Explotación web, webshell y acceso a base de datos', difficulty: 'Advanced', category: 'Initial Access → Persistence', severity: 'critical',
    description: 'Una petición de explotación deriva en una webshell y consultas a la base de datos desde el proceso Apache.',
    briefing: 'Relaciona request-id, integridad de archivos, procesos hijos y conexión a base de datos para medir alcance.',
    businessContext: 'El e-commerce sólo permite despliegues firmados desde CI; Apache no inicia shells ni conecta a la base con clientes interactivos.',
    host: 'ecom-web-02', user: 'apache', sourceIp: '203.0.113.201', verdict: 'true-positive', noiseCount: 168,
    noiseSources: ['http', 'suricata', 'linux', 'network', 'firewall'], alerts: ['Error 500 con patrón de explotación', 'Archivo PHP nuevo en cache', 'Proceso Apache inicia cliente SQL'],
    techniques: [technique('T1190'), technique('T1505.003'), technique('T1059.004')],
    iocs: [{ type: 'ip', value: '203.0.113.201', context: 'Origen de explotación y control' }, { type: 'path', value: '/var/www/html/cache/theme.php', context: 'Webshell sintética' }],
    events: [
      e(36, 'http', 'ecom-web-02', 'anonymous', '203.0.113.201', '500', 'web_request', 'failure', 'POST /catalog/import caused deserialization exception request-id rq-71bb', { uri: '/catalog/import', request_id: 'rq-71bb' }),
      e(36.2, 'suricata', 'waf-03', 'anonymous', '203.0.113.201', 'SURICATA-2100511', 'exploit_attempt', 'unknown', 'Serialized object markers observed in rq-71bb', { request_id: 'rq-71bb' }),
      e(38, 'linux', 'ecom-web-02', 'apache', '203.0.113.201', 'FIM', 'file_create', 'success', '/var/www/html/cache/theme.php created by httpd', { path: '/var/www/html/cache/theme.php', hash: '113ca8ef-synthetic' }),
      e(42, 'http', 'ecom-web-02', 'apache', '203.0.113.201', '200', 'web_request', 'success', 'POST /cache/theme.php action=system returned 32 bytes', { uri: '/cache/theme.php' }),
      e(42.1, 'linux', 'ecom-web-02', 'apache', '203.0.113.201', 'execve', 'process_start', 'success', 'httpd spawned /bin/bash -c id', { parent: 'httpd', process: '/bin/bash' }),
      e(46, 'linux', 'ecom-web-02', 'apache', '203.0.113.201', 'execve', 'process_start', 'success', '/bin/bash spawned mysql -h db-ecom-01 -e show databases', { parent: '/bin/bash', process: 'mysql' }),
      e(47, 'network', 'db-ecom-01', 'app_read', '10.40.17.42', 'MYSQL-CONNECT', 'database_connect', 'success', 'Database connection from ecom-web-02 used app_read credential', { query: 'show databases' }),
      e(58, 'linux', 'ecom-web-02', 'deploy.ci', '10.40.5.62', 'DEPLOY', 'application_deploy', 'success', 'Approved asset deployment from CI runner', { ticket: 'REL-9920' }),
    ],
    pivot: { prompt: '¿Qué identificador correlaciona el WAF con el error de aplicación?', value: 'rq-71bb', evidenceTerms: ['rq-71bb'] },
    scope: { prompt: '¿Qué segundo host fue alcanzado desde la webshell?', value: 'db-ecom-01', evidenceTerms: ['db-ecom-01', 'MYSQL-CONNECT'] },
    explanation: 'rq-71bb conecta explotación y error; httpd crea theme.php, después genera bash y mysql hacia db-ecom-01. El despliegue CI tiene un origen distinto y ticket válido.',
    response: ['Retirar ecom-web-02 del servicio y aislarlo de db-ecom-01', 'Bloquear 203.0.113.201 y preservar theme.php'],
    remediation: ['Recrear el nodo, rotar app_read y revisar consultas a DB', 'Corregir deserialización e impedir escritura del usuario Apache en webroot'],
    kql: ['details.request_id:"rq-71bb" or message:"theme.php"', 'host:("ecom-web-02" or "db-ecom-01") and action:("process_start" or "database_connect")'],
    spl: ['index=soc details.request_id=rq-71bb OR message="*theme.php" | sort timestamp', 'index=soc host IN (ecom-web-02,db-ecom-01) action IN (process_start,database_connect)'],
    sigmaSelection: 'details.parent: httpd\n    details.process: /bin/bash',
  }),
  makeScenario({
    id: 'endpoint-c2-exfiltration', title: 'Endpoint, C2 y exfiltración por canal web', difficulty: 'Advanced', category: 'Command and Control → Exfiltration', severity: 'critical',
    description: 'Un ejecutable presentado como caché de colaboración establece C2, archiva documentos y envía fragmentos.',
    briefing: 'Demuestra las tres fases y calcula qué artefactos y destinos forman parte del mismo proceso.',
    businessContext: 'Dirección usa una suite de colaboración firmada; los ejecutables no residen en Temp ni comprimen el directorio Legal.',
    host: 'exec-wks-03', user: 'raul.mena', sourceIp: '10.40.55.33', verdict: 'true-positive', noiseCount: 182,
    noiseSources: ['endpoint', 'sysmon', 'dns', 'network', 'firewall', 'http', 'windows'], alerts: ['Binario no firmado imita aplicación corporativa', 'TLS periódico seguido de subida fragmentada', 'Compresión de documentos sensibles'],
    techniques: [technique('T1204.002'), technique('T1071.001'), technique('T1560.001'), technique('T1041')],
    iocs: [{ type: 'domain', value: 'media-sync-edge.example', context: 'C2 y receptor sintético' }, { type: 'hash', value: '4a77be20-synthetic', context: 'Hash de TeamsCache.exe' }, { type: 'path', value: 'C:\\Users\\raul.mena\\AppData\\Local\\Temp\\cache.dat', context: 'Archivo preparado' }],
    events: [
      e(31, 'endpoint', 'exec-wks-03', 'raul.mena', '10.40.55.33', 'PROC-START', 'process_start', 'success', 'C:\\Users\\raul.mena\\AppData\\Local\\Temp\\TeamsCache.exe started after user opened meeting-notes.zip', { process: 'TeamsCache.exe', hash: '4a77be20-synthetic', signed: false }),
      e(34, 'dns', 'exec-wks-03', 'raul.mena', '10.40.55.33', 'DNS-Q', 'dns_query', 'success', 'Query A media-sync-edge.example', { domain: 'media-sync-edge.example' }),
      e(35, 'network', 'exec-wks-03', 'raul.mena', '10.40.55.33', 'TLS', 'tls_connect', 'success', 'TeamsCache.exe opened TLS session with stable JA3', { destination: '192.0.2.188', ja3: 'e7d705a3286e' }, '192.0.2.188'),
      e(37, 'network', 'exec-wks-03', 'raul.mena', '10.40.55.33', 'TLS', 'tls_connect', 'success', 'Second 120-second beacon to media-sync-edge.example', { interval_seconds: 120, bytes_out: 488 }, '192.0.2.188'),
      e(48, 'sysmon', 'exec-wks-03', 'raul.mena', '10.40.55.33', '1', 'process_start', 'success', 'TeamsCache.exe spawned tar.exe to archive C:\\Legal\\Board', { parent: 'TeamsCache.exe', process: 'tar.exe' }),
      e(51, 'endpoint', 'exec-wks-03', 'raul.mena', '10.40.55.33', 'FILE-NEW', 'file_create', 'success', 'C:\\Users\\raul.mena\\AppData\\Local\\Temp\\cache.dat created', { bytes: 25165824 }),
      e(54, 'http', 'proxy-02', 'raul.mena', '10.40.55.33', 'POST-206', 'upload', 'success', 'Eight chunked POST requests sent to media-sync-edge.example/api/sync', { chunks: 8, bytes: 25165824 }),
      e(55, 'firewall', 'egress-fw-02', 'raul.mena', '10.40.55.33', 'RESET', 'connection_blocked', 'success', 'Remaining TLS session reset after DLP verdict', { destination: '192.0.2.188' }),
      e(71, 'endpoint', 'exec-wks-03', 'SYSTEM', '10.40.55.33', 'PROC-START', 'process_start', 'success', 'Signed Teams.exe performed normal update check', { process: 'Teams.exe', signed: true }),
    ],
    pivot: { prompt: '¿Qué proceso padre inicia la compresión de documentos?', value: 'TeamsCache.exe', evidenceTerms: ['TeamsCache.exe', 'tar.exe'] },
    scope: { prompt: '¿Qué volumen fue preparado y enviado en fragmentos?', value: '25165824 bytes', aliases: ['24 MB', '25165824'], evidenceTerms: ['25165824'] },
    explanation: 'El binario no firmado establece beaconing, inicia tar sobre Legal y crea cache.dat del mismo tamaño que los ocho POST. Teams.exe firmado posterior es actividad legítima distinta.',
    response: ['Aislar exec-wks-03 y bloquear media-sync-edge.example', 'Preservar memoria, TeamsCache.exe y cache.dat'],
    remediation: ['Rotar secretos accesibles por raul.mena y evaluar datos expuestos', 'Aplicar allowlisting y DLP para archivos de Dirección'],
    kql: ['host:"exec-wks-03" and details.process:("TeamsCache.exe" or "tar.exe")', 'details.domain:"media-sync-edge.example" or details.destination:"192.0.2.188"'],
    spl: ['index=soc host=exec-wks-03 details.process IN (TeamsCache.exe,tar.exe) | sort timestamp', 'index=soc details.domain=media-sync-edge.example OR details.destination=192.0.2.188'],
    sigmaSelection: 'details.parent: TeamsCache.exe\n    details.process: tar.exe',
  }),
  makeScenario({
    id: 'phishing-credential-cloud-abuse', title: 'Phishing, robo de credenciales y abuso cloud', difficulty: 'Advanced', category: 'Initial Access → Cloud Abuse', severity: 'critical',
    description: 'Un enlace de revisión conduce a captura de credenciales y a una sesión cloud que crea persistencia en el buzón.',
    briefing: 'Correlaciona mensaje, navegación, POST, identidad cloud, regla de correo y acceso a ficheros.',
    businessContext: 'Legal comparte documentos sólo mediante el tenant corporativo; las reglas de reenvío externo están prohibidas.',
    host: 'entra-id', user: 'elena.vico', sourceIp: '192.0.2.211', verdict: 'true-positive', noiseCount: 176,
    noiseSources: ['email', 'dns', 'http', 'cloud', 'auth', 'firewall'], alerts: ['URL de login no federada', 'Inicio cloud desde dispositivo desconocido', 'Regla de reenvío externo'],
    techniques: [technique('T1566.002'), technique('T1056.003'), technique('T1078.004')],
    iocs: [{ type: 'domain', value: 'secure-docs-login.example', context: 'Portal sintético de captura' }, { type: 'ip', value: '192.0.2.211', context: 'Origen del abuso cloud' }],
    events: [
      e(25, 'email', 'mail-gw-02', 'elena.vico', '198.51.100.44', 'MSG-DELIVERED', 'mail_deliver', 'success', 'External document review message delivered with QR fallback link', { url: 'https://secure-docs-login.example/review' }),
      e(31, 'dns', 'legal-wks-07', 'elena.vico', '10.40.57.27', 'DNS-Q', 'dns_query', 'success', 'Query A secure-docs-login.example', { domain: 'secure-docs-login.example' }),
      e(32, 'http', 'proxy-02', 'elena.vico', '10.40.57.27', 'POST-200', 'form_submit', 'success', 'POST /session/validate sent username and password-sized fields', { domain: 'secure-docs-login.example', request_bytes: 612 }),
      e(39, 'cloud', 'entra-id', 'elena.vico', '192.0.2.211', 'AAD-SUCCESS', 'cloud_login', 'success', 'Cloud login succeeded from unregistered Linux browser', { device_id: 'unknown', mfa_method: 'session-token' }),
      e(42, 'cloud', 'exchange-online', 'elena.vico', '192.0.2.211', 'NEW-INBOXRULE', 'mail_rule_create', 'success', 'Inbox rule ArchiveReview forwards legal-review subjects externally', { forward_to: 'review.archive@external.example' }),
      e(46, 'cloud', 'sharepoint', 'elena.vico', '192.0.2.211', 'FILE-DOWNLOAD', 'bulk_download', 'success', 'Thirty-eight files downloaded from Matter-Delta workspace', { count: 38 }),
      e(54, 'auth', 'entra-id', 'elena.vico', '10.40.57.27', 'MFA-DENY', 'mfa_challenge', 'failure', 'Registered user denied unexpected MFA prompt', { device_id: 'legal-wks-07' }),
      e(63, 'cloud', 'entra-id', 'elena.vico', '10.40.57.27', 'TOKEN-REVOKE', 'session_revoke', 'success', 'Security team revoked all active sessions', { actor: 'soc.analyst' }),
    ],
    pivot: { prompt: '¿Qué acción cloud proporciona persistencia después del login?', value: 'NEW-INBOXRULE', aliases: ['Inbox rule', 'mail_rule_create'], evidenceTerms: ['NEW-INBOXRULE', 'forward_to'] },
    scope: { prompt: '¿Qué espacio cloud fue accedido de forma masiva?', value: 'Matter-Delta', evidenceTerms: ['Matter-Delta', '38'] },
    explanation: 'El POST al dominio ajeno precede al login desde 192.0.2.211; después se crea una regla externa y se descargan 38 ficheros. El MFA rechazado confirma que la usuaria no inició la sesión.',
    response: ['Revocar sesiones de elena.vico y deshabilitar temporalmente la cuenta', 'Eliminar la regla y bloquear dominio, IP y destinatario externo'],
    remediation: ['Restablecer credenciales y registrar MFA nuevo', 'Buscar el dominio y la regla en todo el tenant y evaluar Matter-Delta'],
    kql: ['user:"elena.vico" and action:("form_submit" or "cloud_login" or "mail_rule_create" or "bulk_download")', 'sourceIp:"192.0.2.211" or details.domain:"secure-docs-login.example"'],
    spl: ['index=soc user=elena.vico action IN (form_submit,cloud_login,mail_rule_create,bulk_download) | sort timestamp', 'index=soc sourceIp=192.0.2.211 OR details.domain=secure-docs-login.example'],
    sigmaSelection: 'action: mail_rule_create\n    details.forward_to|endswith: external.example',
  }),
];
