import { technique } from '../mitre.js';
import { e, makeScenario } from './shared.js';

export const groupBScenarios = [
  makeScenario({
    id: 'phishing-powershell', title: 'Enlace de phishing y ejecución PowerShell', difficulty: 'Intermediate', category: 'Initial Access → Execution', severity: 'critical',
    description: 'Un enlace recibido por correo deriva en PowerShell iniciado desde el navegador y tráfico posterior.',
    briefing: 'Une entrega, clic, resolución DNS, árbol de procesos y salida de red para demostrar la cadena completa.',
    businessContext: 'Contabilidad recibe enlaces de proveedores, pero los documentos se abren en el portal corporativo y nunca requieren scripts.',
    host: 'acct-wks-05', user: 'vera.soler', sourceIp: '192.0.2.74', verdict: 'true-positive', noiseCount: 88,
    noiseSources: ['email', 'dns', 'http', 'endpoint', 'sysmon', 'windows'], alerts: ['Correo con URL recién observada', 'PowerShell hijo de navegador'],
    techniques: [technique('T1566.002'), technique('T1059.001')],
    iocs: [{ type: 'domain', value: 'document-review.example', context: 'Dominio de redirección del enlace' }, { type: 'hash', value: 'c82f3d10-synthetic', context: 'Script recuperado en memoria' }],
    events: [
      e(22, 'email', 'mail-gw-02', 'vera.soler', '192.0.2.74', 'MSG-DELIVERED', 'mail_deliver', 'success', 'Message Payment advice available delivered with link', { sender: 'billing@partner-review.example', url: 'https://document-review.example/d/1842' }),
      e(27, 'dns', 'acct-wks-05', 'vera.soler', '10.40.42.35', 'DNS-Q', 'dns_query', 'success', 'Query A document-review.example', { domain: 'document-review.example' }),
      e(28, 'http', 'proxy-02', 'vera.soler', '10.40.42.35', '302', 'web_request', 'success', 'GET /d/1842 redirected to ms-appinstaller handler', { domain: 'document-review.example' }),
      e(30, 'sysmon', 'acct-wks-05', 'vera.soler', '10.40.42.35', '1', 'process_start', 'success', 'msedge.exe spawned powershell.exe with hidden window', { parent: 'msedge.exe', process: 'powershell.exe' }),
      e(31, 'windows', 'acct-wks-05', 'vera.soler', '10.40.42.35', '4104', 'script_block', 'success', 'PowerShell decoded a memory buffer and invoked WebClient', { script_hash: 'c82f3d10-synthetic' }),
      e(33, 'endpoint', 'acct-wks-05', 'vera.soler', '10.40.42.35', 'MEM-BLOCK', 'behavior_block', 'success', 'Endpoint blocked in-memory script after suspicious parent-child chain', { parent: 'msedge.exe' }),
    ],
    pivot: { prompt: '¿Qué proceso padre vincula el clic web con PowerShell?', value: 'msedge.exe', evidenceTerms: ['msedge.exe', 'powershell.exe'] },
    scope: { prompt: '¿Qué endpoint ejecutó el contenido y fue bloqueado?', value: 'acct-wks-05', evidenceTerms: ['acct-wks-05'] },
    explanation: 'El mensaje y DNS sólo establecen exposición; la redirección de protocolo y el árbol msedge→PowerShell, confirmado por 4104 y EDR, prueban ejecución.',
    response: ['Aislar acct-wks-05 y preservar la memoria de PowerShell', 'Purgar el mensaje y bloquear el dominio'],
    remediation: ['Rotar las credenciales de vera.soler', 'Bloquear handlers externos y PowerShell no firmado desde navegadores'],
    kql: ['user:"vera.soler" and source:("email" or "dns" or "http")', 'host:"acct-wks-05" and details.parent:"msedge.exe" and details.process:"powershell.exe"'],
    spl: ['index=soc user=vera.soler source IN (email,dns,http) | sort timestamp', 'index=soc host=acct-wks-05 details.parent=msedge.exe details.process=powershell.exe'],
    sigmaSelection: 'details.parent: msedge.exe\n    details.process: powershell.exe',
  }),
  makeScenario({
    id: 'web-account-privilege-abuse', title: 'Cuenta web comprometida y abuso de privilegios', difficulty: 'Intermediate', category: 'Persistence', severity: 'high',
    description: 'Una cuenta de soporte inicia sesión con sesión válida y concede un rol elevado a otra identidad.',
    briefing: 'Distingue el inicio de sesión comprometido de la actividad diaria y reconstruye los cambios de permisos.',
    businessContext: 'El portal CRM usa roles temporales aprobados por ticket; los analistas de soporte no pueden conceder roles globales.',
    host: 'crm-admin-01', user: 'helpdesk.jdiaz', sourceIp: '198.51.100.171', verdict: 'true-positive', noiseCount: 94,
    noiseSources: ['auth', 'http', 'cloud', 'firewall'], alerts: ['Sesión con cookie válida desde ASN nuevo', 'Rol privilegiado concedido sin ticket'],
    techniques: [technique('T1078'), technique('T1098.003')],
    iocs: [{ type: 'ip', value: '198.51.100.171', context: 'Origen de la sesión secuestrada' }, { type: 'user', value: 'ops.sync', context: 'Cuenta a la que se añadió el rol' }],
    events: [
      e(35, 'auth', 'crm-admin-01', 'helpdesk.jdiaz', '198.51.100.171', 'SESSION-RESUME', 'session_resume', 'success', 'Existing web session resumed without new MFA challenge', { device_id: 'unknown-77' }),
      e(37, 'http', 'crm-admin-01', 'helpdesk.jdiaz', '198.51.100.171', '200', 'admin_page_view', 'success', 'GET /admin/roles from previously unseen browser fingerprint', { fingerprint: 'fp-31a9' }),
      e(41, 'cloud', 'crm-admin-01', 'helpdesk.jdiaz', '198.51.100.171', 'ROLE-ADD', 'role_change', 'success', 'TenantSupportAdmin role added to ops.sync', { target_user: 'ops.sync', role: 'TenantSupportAdmin', ticket: 'none' }),
      e(44, 'cloud', 'crm-admin-01', 'ops.sync', '198.51.100.171', 'API-TOKEN', 'token_create', 'success', 'API token created by newly privileged account', { token_scope: 'customers.read' }),
      e(48, 'http', 'crm-admin-01', 'ops.sync', '198.51.100.171', '200', 'bulk_export', 'success', 'Customer metadata export requested via API', { records: 2140 }),
      e(54, 'auth', 'crm-admin-01', 'helpdesk.jdiaz', '10.40.6.19', 'LOGIN', 'login', 'success', 'Normal helpdesk session began from managed workstation with MFA', { mfa: true }),
    ],
    pivot: { prompt: '¿Qué rol fue concedido sin aprobación?', value: 'TenantSupportAdmin', evidenceTerms: ['TenantSupportAdmin', 'ROLE-ADD'] },
    scope: { prompt: '¿Qué segunda cuenta pasó a formar parte del incidente?', value: 'ops.sync', evidenceTerms: ['ops.sync'] },
    explanation: 'La cookie válida evita fallos de contraseña, pero el dispositivo desconocido, el ROLE-ADD sin ticket y el token de ops.sync demuestran secuestro y expansión de privilegios.',
    response: ['Revocar las sesiones de helpdesk.jdiaz y ops.sync', 'Retirar TenantSupportAdmin y revocar el token'],
    remediation: ['Rotar ambas credenciales y revisar exportaciones', 'Exigir reautenticación MFA para cambios de rol'],
    kql: ['host:"crm-admin-01" and action:("session_resume" or "role_change" or "token_create")', 'sourceIp:"198.51.100.171" and user:("helpdesk.jdiaz" or "ops.sync")'],
    spl: ['index=soc host=crm-admin-01 action IN (session_resume,role_change,token_create) | sort timestamp', 'index=soc sourceIp=198.51.100.171 | stats values(action) by user'],
    sigmaSelection: 'action: role_change\n    details.ticket: none',
  }),
  makeScenario({
    id: 'suspicious-smb', title: 'Actividad SMB anómala entre segmentos', difficulty: 'Intermediate', category: 'Discovery / Lateral Movement', severity: 'high',
    description: 'Una estación de laboratorio enumera recursos y accede a un recurso administrativo fuera de su segmento.',
    briefing: 'Correlaciona comandos del endpoint, firewall y auditoría de recursos compartidos para determinar alcance.',
    businessContext: 'El escáner documental usa SMB sólo desde svc.scanner; el segmento de laboratorio no necesita acceso a servidores financieros.',
    host: 'lab-wks-09', user: 'svc.scanner', sourceIp: '10.40.44.19', verdict: 'true-positive', noiseCount: 96,
    noiseSources: ['windows', 'sysmon', 'network', 'firewall'], alerts: ['Enumeración SMB desde segmento de laboratorio', 'Acceso a ADMIN$ con cuenta de servicio'],
    techniques: [technique('T1135'), technique('T1021.002')], iocs: [{ type: 'ip', value: '10.40.44.19', context: 'Origen no autorizado de SMB' }],
    events: [
      e(26, 'sysmon', 'lab-wks-09', 'svc.scanner', '10.40.44.19', '1', 'process_start', 'success', 'cmd.exe launched net.exe view \\file-core-01', { parent: 'cmd.exe', process: 'net.exe' }),
      e(28, 'firewall', 'seg-fw-02', 'svc.scanner', '10.40.44.19', 'ALLOW-445', 'connection_allowed', 'success', 'SMB allowed from lab-wks-09 to file-core-01 by legacy rule', { destination_port: 445 }, '10.40.12.51'),
      e(29, 'windows', 'file-core-01', 'svc.scanner', '10.40.44.19', '5140', 'share_access', 'success', 'Network share IPC$ accessed', { share: 'IPC$' }),
      e(31, 'windows', 'file-core-01', 'svc.scanner', '10.40.44.19', '5145', 'share_access', 'success', 'Administrative share ADMIN$ accessed; relative target System32', { share: 'ADMIN$' }),
      e(34, 'network', 'file-core-01', 'svc.scanner', '10.40.44.19', 'SMB-WRITE', 'file_write', 'success', 'Binary staged to ADMIN$\\Temp\\spoolsvc.exe', { bytes: 92160 }),
      e(39, 'windows', 'print-01', 'svc.scanner', '10.40.18.15', '5140', 'share_access', 'success', 'Expected scans share accessed from approved scanner', { share: 'scans' }),
    ],
    pivot: { prompt: '¿Qué recurso compartido demuestra acceso administrativo?', value: 'ADMIN$', evidenceTerms: ['ADMIN$', '5145'] },
    scope: { prompt: '¿Qué servidor recibió el binario por SMB?', value: 'file-core-01', evidenceTerms: ['file-core-01', 'spoolsvc.exe'] },
    explanation: 'La actividad legítima procede de print-01; lab-wks-09 ejecuta net view, cruza el firewall por una regla heredada y escribe en ADMIN$ de file-core-01.',
    response: ['Aislar lab-wks-09 y bloquear SMB entre segmentos', 'Deshabilitar svc.scanner hasta rotar su secreto'],
    remediation: ['Eliminar la regla heredada y revisar spoolsvc.exe', 'Restringir la cuenta a print-01 y al recurso scans'],
    kql: ['sourceIp:"10.40.44.19" and action:("connection_allowed" or "share_access" or "file_write")', 'details.share:"ADMIN$" or message:"spoolsvc.exe"'],
    spl: ['index=soc sourceIp=10.40.44.19 | transaction user maxspan=20m', 'index=soc details.share="ADMIN$" OR message="*spoolsvc.exe"'],
    sigmaSelection: 'eventCode: 5145\n    details.share: "ADMIN$"',
  }),
  makeScenario({
    id: 'dns-beaconing', title: 'Beaconing DNS de baja cadencia', difficulty: 'Intermediate', category: 'Command and Control', severity: 'high',
    description: 'Consultas pequeñas y periódicas se mezclan con la telemetría DNS normal de una estación de desarrollo.',
    briefing: 'Diferencia actualización legítima, túnel de datos y beacon de control usando cadencia, proceso y volumen.',
    businessContext: 'Desarrollo ejecuta agentes que consultan dominios internos, pero sólo binarios firmados pueden resolver dominios externos periódicamente.',
    host: 'dev-wks-14', user: 'marcos.arias', sourceIp: '10.40.47.64', verdict: 'true-positive', noiseCount: 101,
    noiseSources: ['dns', 'network', 'endpoint', 'sysmon'], alerts: ['Dominio nuevo consultado cada 90 segundos', 'Resolver originado por binario sin firma'],
    techniques: [technique('T1071.004')], iocs: [{ type: 'domain', value: 'edge-status-cache.example', context: 'Dominio de beacon DNS' }, { type: 'hash', value: 'f1039b8e-synthetic', context: 'Hash del proceso originador' }],
    events: [
      e(20, 'endpoint', 'dev-wks-14', 'marcos.arias', '10.40.47.64', 'PROC-START', 'process_start', 'success', 'C:\\ProgramData\\EdgeTools\\updater-host.exe started without valid signature', { process: 'updater-host.exe', hash: 'f1039b8e-synthetic', signed: false }),
      e(22, 'dns', 'dev-wks-14', 'marcos.arias', '10.40.47.64', 'DNS-Q', 'dns_query', 'success', 'Query A n17.edge-status-cache.example', { domain: 'edge-status-cache.example', response_bytes: 96 }),
      e(23.5, 'dns', 'dev-wks-14', 'marcos.arias', '10.40.47.64', 'DNS-Q', 'dns_query', 'success', 'Query A n18.edge-status-cache.example', { domain: 'edge-status-cache.example', interval_seconds: 90 }),
      e(25, 'dns', 'dev-wks-14', 'marcos.arias', '10.40.47.64', 'DNS-Q', 'dns_query', 'success', 'Query A n19.edge-status-cache.example', { domain: 'edge-status-cache.example', interval_seconds: 90 }),
      e(28, 'network', 'dns-02', 'marcos.arias', '10.40.47.64', 'DNS-STATS', 'dns_pattern', 'unknown', 'Low-volume DNS sequence has 90 second median interval and low jitter', { queries: 6, median_interval: 90, bytes: 612 }),
      e(35, 'sysmon', 'dev-wks-14', 'marcos.arias', '10.40.47.64', '5', 'process_end', 'success', 'updater-host.exe stopped after endpoint network isolation', { process: 'updater-host.exe' }),
    ],
    pivot: { prompt: '¿Qué cadencia distingue el beacon del resto del DNS?', value: '90 seconds', aliases: ['90 segundos', '90'], evidenceTerms: ['90'] },
    scope: { prompt: '¿Qué proceso origina el patrón DNS?', value: 'updater-host.exe', evidenceTerms: ['updater-host.exe'] },
    explanation: 'El volumen es demasiado bajo para túnel; la periodicidad estable, los subdominios secuenciales y el binario sin firma confirman beaconing DNS.',
    response: ['Aislar dev-wks-14 y detener updater-host.exe', 'Bloquear edge-status-cache.example en DNS'],
    remediation: ['Adquirir el binario y buscar su hash en el entorno', 'Aplicar control de firma a procesos que realizan DNS externo'],
    kql: ['host:"dev-wks-14" and details.domain:"edge-status-cache.example"', 'action:"dns_pattern" and details.median_interval:90'],
    spl: ['index=soc host=dev-wks-14 details.domain=edge-status-cache.example | sort timestamp', 'index=soc action=dns_pattern details.median_interval=90'],
    sigmaSelection: 'details.domain: edge-status-cache.example',
  }),
  makeScenario({
    id: 'credential-dumping', title: 'Indicadores de volcado de credenciales', difficulty: 'Intermediate', category: 'Credential Access', severity: 'critical',
    description: 'Un binario renombrado abre LSASS y crea un archivo temporal antes de ser bloqueado.',
    briefing: 'Demuestra el intento mediante acceso a proceso, privilegios, línea de comandos y artefacto, no sólo por el nombre del binario.',
    businessContext: 'El equipo de soporte puede recopilar dumps de aplicaciones, pero nunca de procesos protegidos ni desde estaciones de usuario.',
    host: 'support-wks-04', user: 'tier2.molina', sourceIp: '10.40.49.34', verdict: 'true-positive', noiseCount: 98,
    noiseSources: ['windows', 'sysmon', 'endpoint'], alerts: ['Acceso a LSASS desde proceso no firmado', 'Archivo .dmp creado en ProgramData'],
    techniques: [technique('T1003.001')], iocs: [{ type: 'path', value: 'C:\\ProgramData\\diag\\cache.dmp', context: 'Dump sintético bloqueado' }, { type: 'hash', value: '82ef09ac-synthetic', context: 'Hash del ejecutable renombrado' }],
    events: [
      e(18, 'windows', 'support-wks-04', 'tier2.molina', '10.40.49.34', '4672', 'privilege_assign', 'success', 'SeDebugPrivilege assigned to elevated interactive session', { privilege: 'SeDebugPrivilege' }),
      e(20, 'sysmon', 'support-wks-04', 'tier2.molina', '10.40.49.34', '1', 'process_start', 'success', 'cmd.exe spawned C:\\Users\\Public\\werdiag.exe -ma lsass.exe cache.dmp', { parent: 'cmd.exe', process: 'werdiag.exe', hash: '82ef09ac-synthetic' }),
      e(21, 'sysmon', 'support-wks-04', 'tier2.molina', '10.40.49.34', '10', 'process_access', 'success', 'werdiag.exe opened lsass.exe with PROCESS_VM_READ', { target_process: 'lsass.exe', granted_access: '0x1010' }),
      e(22, 'endpoint', 'support-wks-04', 'tier2.molina', '10.40.49.34', 'FILE-NEW', 'file_create', 'success', 'C:\\ProgramData\\diag\\cache.dmp created then locked by EDR', { path: 'C:\\ProgramData\\diag\\cache.dmp' }),
      e(23, 'endpoint', 'support-wks-04', 'tier2.molina', '10.40.49.34', 'BLOCK', 'behavior_block', 'success', 'Credential access behavior blocked and werdiag.exe terminated', { process: 'werdiag.exe' }),
    ],
    pivot: { prompt: '¿Qué proceso objetivo confirma el intento de volcado?', value: 'lsass.exe', evidenceTerms: ['lsass.exe', '0x1010'] },
    scope: { prompt: '¿Qué archivo fue creado antes del bloqueo?', value: 'C:\\ProgramData\\diag\\cache.dmp', aliases: ['cache.dmp'], evidenceTerms: ['cache.dmp'] },
    explanation: 'SeDebugPrivilege, la línea -ma, Sysmon 10 contra LSASS y el dump temporal forman evidencia convergente aun cuando werdiag.exe intenta parecer legítimo.',
    response: ['Aislar support-wks-04 y preservar cache.dmp', 'Deshabilitar tier2.molina y revocar sus sesiones'],
    remediation: ['Rotar credenciales usadas en el equipo', 'Aplicar protección LSA y retirar privilegios locales al soporte'],
    kql: ['host:"support-wks-04" and eventCode:("4672" or "10")', 'details.target_process:"lsass.exe" or message:"cache.dmp"'],
    spl: ['index=soc host=support-wks-04 eventCode IN (4672,10) | sort timestamp', 'index=soc details.target_process=lsass.exe OR message="*cache.dmp"'],
    sigmaSelection: 'eventCode: 10\n    details.target_process: lsass.exe',
  }),
  makeScenario({
    id: 'lateral-movement-remote-services', title: 'Movimiento lateral mediante WinRM', difficulty: 'Intermediate', category: 'Lateral Movement', severity: 'critical',
    description: 'Una cuenta de despliegue abre sesiones WinRM en dos servidores fuera de la ventana CI/CD.',
    briefing: 'Correlaciona autenticación, firewall, WinRM y PowerShell remoto para identificar origen y destinos.',
    businessContext: 'svc.deploy sólo puede usar WinRM desde runner-ci-01 entre las 02:00 y 03:00 UTC.',
    host: 'it-wks-22', user: 'svc.deploy', sourceIp: '10.40.52.22', verdict: 'true-positive', noiseCount: 104,
    noiseSources: ['auth', 'windows', 'firewall', 'network', 'sysmon'], alerts: ['WinRM desde estación de usuario', 'Cuenta de despliegue usada fuera de ventana'],
    techniques: [technique('T1021.006'), technique('T1078.002')], iocs: [{ type: 'ip', value: '10.40.52.22', context: 'Origen de las sesiones remotas' }],
    events: [
      e(29, 'auth', 'dc-02', 'svc.deploy', '10.40.52.22', '4768', 'ticket_request', 'success', 'Kerberos TGT requested for svc.deploy from it-wks-22', { workstation: 'it-wks-22' }),
      e(31, 'firewall', 'seg-fw-03', 'svc.deploy', '10.40.52.22', 'ALLOW-5985', 'connection_allowed', 'success', 'WinRM traffic allowed to app-02 by broad management rule', { destination_port: 5985 }, '10.40.15.22'),
      e(32, 'windows', 'app-02', 'svc.deploy', '10.40.52.22', '4624', 'login', 'success', 'Network logon type 3 for svc.deploy', { logon_type: 3 }),
      e(33, 'windows', 'app-02', 'svc.deploy', '10.40.52.22', '91', 'winrm_shell', 'success', 'WinRM shell created from it-wks-22', { shell_id: 'winrm-8fa2' }),
      e(35, 'sysmon', 'app-02', 'svc.deploy', '10.40.52.22', '1', 'process_start', 'success', 'wsmprovhost.exe spawned powershell.exe whoami /all', { parent: 'wsmprovhost.exe', process: 'powershell.exe' }),
      e(40, 'windows', 'app-03', 'svc.deploy', '10.40.52.22', '91', 'winrm_shell', 'success', 'Second WinRM shell created from it-wks-22', { shell_id: 'winrm-3b77' }),
      e(49, 'network', 'runner-ci-01', 'svc.deploy', '10.40.5.31', 'WINRM-BASELINE', 'winrm_session', 'success', 'Approved deployment health check to app-04', { ticket: 'DEPLOY-8831' }),
    ],
    pivot: { prompt: '¿Qué proceso padre identifica ejecución mediante WinRM?', value: 'wsmprovhost.exe', evidenceTerms: ['wsmprovhost.exe', 'powershell.exe'] },
    scope: { prompt: '¿Qué dos servidores recibieron sesiones remotas?', value: 'app-02 and app-03', aliases: ['app-02 y app-03', 'app-02, app-03'], evidenceTerms: ['app-02', 'app-03'] },
    explanation: 'La línea base válida nace en runner-ci-01; los tickets, puerto 5985, evento 91 y wsmprovhost enlazan it-wks-22 con app-02 y app-03.',
    response: ['Aislar it-wks-22 y cerrar las sesiones WinRM', 'Deshabilitar svc.deploy y revocar tickets Kerberos'],
    remediation: ['Rotar el secreto de despliegue', 'Limitar WinRM a runners aprobados y ventanas CI/CD'],
    kql: ['sourceIp:"10.40.52.22" and eventCode:("4768" or "91" or "ALLOW-5985")', 'details.parent:"wsmprovhost.exe"'],
    spl: ['index=soc sourceIp=10.40.52.22 eventCode IN (4768,91,ALLOW-5985) | sort timestamp', 'index=soc details.parent=wsmprovhost.exe | stats values(host) by user'],
    sigmaSelection: 'eventCode: 91\n    sourceIp: 10.40.52.22',
  }),
  makeScenario({
    id: 'registry-run-keys', title: 'Persistencia mediante Registry Run Keys', difficulty: 'Intermediate', category: 'Persistence', severity: 'high',
    description: 'Una clave Run apunta a un script en AppData tras una cadena mshta→reg.exe.',
    briefing: 'Correlaciona árbol de procesos, cambio de registro, archivo y ejecución al siguiente logon.',
    businessContext: 'Los agentes corporativos usan servicios MSI; ninguna aplicación aprobada crea claves Run desde mshta.',
    host: 'design-wks-06', user: 'luis.cano', sourceIp: '10.40.53.46', verdict: 'true-positive', noiseCount: 99,
    noiseSources: ['sysmon', 'windows', 'endpoint', 'dns'], alerts: ['Sysmon 13 en clave Run', 'reg.exe iniciado por mshta.exe'],
    techniques: [technique('T1547.001')], iocs: [{ type: 'path', value: 'C:\\Users\\luis.cano\\AppData\\Roaming\\ColorSync\\sync.js', context: 'Script persistente' }],
    events: [
      e(24, 'sysmon', 'design-wks-06', 'luis.cano', '10.40.53.46', '1', 'process_start', 'success', 'mshta.exe spawned reg.exe ADD HKCU Run ColorSync', { parent: 'mshta.exe', process: 'reg.exe' }),
      e(25, 'sysmon', 'design-wks-06', 'luis.cano', '10.40.53.46', '13', 'registry_value_set', 'success', 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\ColorSync set', { registry_path: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\ColorSync', value: 'wscript.exe %APPDATA%\\ColorSync\\sync.js' }),
      e(26, 'endpoint', 'design-wks-06', 'luis.cano', '10.40.53.46', 'FILE-NEW', 'file_create', 'success', 'C:\\Users\\luis.cano\\AppData\\Roaming\\ColorSync\\sync.js created', { hash: 'af01d293-synthetic' }),
      e(61, 'windows', 'design-wks-06', 'luis.cano', '10.40.53.46', '4624', 'login', 'success', 'Interactive logon after workstation unlock', { logon_type: 2 }),
      e(61.2, 'sysmon', 'design-wks-06', 'luis.cano', '10.40.53.46', '1', 'process_start', 'success', 'userinit.exe spawned wscript.exe with ColorSync\\sync.js', { parent: 'userinit.exe', process: 'wscript.exe' }),
      e(63, 'dns', 'design-wks-06', 'luis.cano', '10.40.53.46', 'DNS-Q', 'dns_query', 'success', 'Query A palette-api.example from wscript.exe', { domain: 'palette-api.example' }),
    ],
    pivot: { prompt: '¿Qué valor de registro establece la persistencia?', value: 'ColorSync', evidenceTerms: ['ColorSync', 'registry_value_set'] },
    scope: { prompt: '¿Qué script se ejecuta tras el siguiente logon?', value: 'sync.js', aliases: ['ColorSync\\sync.js'], evidenceTerms: ['sync.js', 'userinit.exe'] },
    explanation: 'La relación mshta→reg, Sysmon 13, creación del JS y ejecución posterior desde userinit demuestran persistencia efectiva, no sólo una escritura de registro.',
    response: ['Aislar design-wks-06 y exportar la clave Run', 'Bloquear el script y palette-api.example'],
    remediation: ['Eliminar la persistencia tras preservar evidencia', 'Revisar el vector que inició mshta y rotar credenciales'],
    kql: ['host:"design-wks-06" and eventCode:("13" or "1")', 'details.registry_path:"*CurrentVersion\\\\Run*" or message:"sync.js"'],
    spl: ['index=soc host=design-wks-06 eventCode IN (13,1) | sort timestamp', 'index=soc details.registry_path="*CurrentVersion\\Run*" OR message="*sync.js"'],
    sigmaSelection: "eventCode: 13\n    details.registry_path|contains: 'CurrentVersion\\Run'",
  }),
];
