import { technique } from '../mitre.js';
import { e, makeScenario } from './shared.js';

export const groupDScenarios = [
  makeScenario({
    id: 'ambiguous-admin-activity', title: 'Actividad administrativa: ¿incidente o cambio?', difficulty: 'Advanced', category: 'Triage / Remote Administration', severity: 'medium',
    description: 'RDP, PowerShell y reinicios de servicio parecen una intrusión, pero existen señales de un cambio planificado.',
    briefing: 'Correlaciona identidad, dispositivo, ticket, firma de script y ventana para justificar TP o FP con evidencia.',
    businessContext: 'Infraestructura realiza parches urgentes desde un jump host dedicado; toda actividad debe enlazar un ticket aprobado.',
    host: 'dc-03', user: 'carlos.admin', sourceIp: '10.40.5.17', verdict: 'false-positive', noiseCount: 148,
    noiseSources: ['auth', 'windows', 'sysmon', 'firewall', 'endpoint'], alerts: ['RDP a controlador de dominio', 'PowerShell remoto y reinicio de servicio', 'Actividad nocturna privilegiada'],
    techniques: [technique('T1021.001')], iocs: [{ type: 'ip', value: '10.40.5.17', context: 'Jump host validado como origen administrativo' }],
    events: [
      e(44, 'auth', 'pam-01', 'carlos.admin', '10.40.5.17', 'PAM-CHECKOUT', 'privileged_session', 'success', 'Approved credential checkout for CHG-4821', { ticket: 'CHG-4821', approved: true }),
      e(46, 'firewall', 'core-fw-01', 'carlos.admin', '10.40.5.17', 'ALLOW-3389', 'connection_allowed', 'success', 'RDP from admin-jump-01 to dc-03 allowed by management policy', { destination_port: 3389 }, '10.40.10.13'),
      e(47, 'windows', 'dc-03', 'carlos.admin', '10.40.5.17', '4624', 'login', 'success', 'Remote interactive logon type 10 with smartcard', { logon_type: 10, authentication: 'smartcard' }),
      e(51, 'sysmon', 'dc-03', 'carlos.admin', '10.40.5.17', '1', 'process_start', 'success', 'powershell.exe launched signed Patch-KB506821.ps1', { process: 'powershell.exe', script: 'Patch-KB506821.ps1', signed: true }),
      e(55, 'windows', 'dc-03', 'carlos.admin', '10.40.5.17', '7036', 'service_restart', 'success', 'Netlogon service restarted during approved maintenance', { ticket: 'CHG-4821' }),
      e(61, 'endpoint', 'dc-03', 'carlos.admin', '10.40.5.17', 'PATCH-OK', 'patch_install', 'success', 'KB506821 installed; signature and change window validated', { approved: true, ticket: 'CHG-4821' }),
      e(68, 'windows', 'dc-03', 'carlos.admin', '10.40.5.17', '4634', 'logout', 'success', 'Administrative RDP session ended within approved window', { duration_minutes: 21 }),
    ],
    pivot: { prompt: '¿Qué dato externo valida la actividad administrativa?', value: 'CHG-4821', evidenceTerms: ['CHG-4821', 'approved'] },
    scope: { prompt: '¿Qué parche firmado quedó instalado dentro de la ventana?', value: 'KB506821', aliases: ['Patch-KB506821.ps1'], evidenceTerms: ['KB506821', 'PATCH-OK'] },
    explanation: 'RDP y PowerShell son técnicas observables, pero PAM, smartcard, firma, ticket, origen y ventana convergen en un cambio legítimo. La alerta es un falso positivo correctamente investigado.',
    response: ['Validar CHG-4821 y mantener monitorización sin aislar dc-03', 'Documentar el falso positivo con origen y firma'],
    remediation: ['Afinar la detección con contexto PAM sin excluir controladores', 'Exigir que futuros scripts propaguen ticket y firma a la telemetría'],
    kql: ['host:"dc-03" and sourceIp:"10.40.5.17"', 'details.ticket:"CHG-4821" or details.approved:true'],
    spl: ['index=soc host=dc-03 sourceIp=10.40.5.17 | sort timestamp', 'index=soc details.ticket=CHG-4821 OR details.approved=true'],
  }),
  makeScenario({
    id: 'possible-data-exfiltration', title: 'Posible exfiltración o copia autorizada', difficulty: 'Advanced', category: 'Triage / Data Transfer', severity: 'medium',
    description: 'DLP detecta una subida de 4,2 GB a un dominio nuevo con compresión y cifrado.',
    briefing: 'Decide si existe exfiltración correlacionando proceso, contrato, inventario, cuenta de destino y ventana de backup.',
    businessContext: 'Marketing migra su archivo audiovisual a un proveedor europeo recién contratado mediante un agente de backup.',
    host: 'mkt-wks-15', user: 'lucia.rey', sourceIp: '10.40.58.45', verdict: 'false-positive', noiseCount: 162,
    noiseSources: ['endpoint', 'http', 'network', 'cloud', 'firewall', 'windows'], alerts: ['Subida 24 veces sobre baseline', 'Destino cloud observado por primera vez', 'Archivo cifrado antes de transferir'],
    techniques: [technique('T1567.002'), technique('T1560.001')], iocs: [{ type: 'domain', value: 'backup-eu.example', context: 'Destino nuevo validado como proveedor' }],
    events: [
      e(39, 'cloud', 'vendor-risk', 'procurement.bot', '10.40.5.80', 'VENDOR-APPROVED', 'vendor_approval', 'success', 'backup-eu.example approved under contract MKT-2026-44', { approved: true, contract: 'MKT-2026-44' }),
      e(42, 'endpoint', 'mkt-wks-15', 'lucia.rey', '10.40.58.45', 'PROC-START', 'process_start', 'success', 'Signed BackupAgent.exe started scheduled job CreativeArchive', { process: 'BackupAgent.exe', signed: true, job: 'CreativeArchive' }),
      e(46, 'windows', 'mkt-wks-15', 'svc.backup', '10.40.58.45', 'FILE-ARCHIVE', 'archive_create', 'success', 'BackupAgent created encrypted CreativeArchive-0918.bak', { bytes: 4509715660, encryption: true }),
      e(48, 'firewall', 'egress-fw-02', 'svc.backup', '10.40.58.45', 'ALLOW-443', 'connection_allowed', 'success', 'TLS connection to backup-eu.example matched approved vendor policy', { contract: 'MKT-2026-44' }),
      e(52, 'http', 'proxy-02', 'svc.backup', '10.40.58.45', 'PUT-200', 'upload', 'success', 'Multipart upload to backup-eu.example tenant marketing-eu', { domain: 'backup-eu.example', bytes: 4509715660, tenant: 'marketing-eu' }),
      e(57, 'cloud', 'backup-eu', 'svc.backup', '10.40.58.45', 'OBJECT-VERIFY', 'backup_verify', 'success', 'Object checksum verified in corporate tenant marketing-eu', { approved: true, retention_days: 90 }),
      e(60, 'network', 'dlp-01', 'lucia.rey', '10.40.58.45', 'DLP-ALERT', 'data_loss_alert', 'unknown', '4.2 GB encrypted upload exceeded individual user baseline', { bytes: 4509715660 }),
    ],
    pivot: { prompt: '¿Qué proceso firmado realizó la transferencia?', value: 'BackupAgent.exe', evidenceTerms: ['BackupAgent.exe', 'signed'] },
    scope: { prompt: '¿Qué contrato y tenant validan el destino?', value: 'MKT-2026-44 / marketing-eu', aliases: ['MKT-2026-44', 'marketing-eu'], evidenceTerms: ['MKT-2026-44', 'marketing-eu'] },
    explanation: 'El volumen y cifrado disparan DLP, pero contrato, binario firmado, política de firewall, tenant corporativo y checksum prueban una migración autorizada. No debe bloquearse como exfiltración.',
    response: ['Validar MKT-2026-44 y permitir finalizar la copia', 'Registrar backup-eu.example como destino aprobado con alcance limitado'],
    remediation: ['Asociar jobs de backup con contratos en DLP', 'Usar cuenta de servicio dedicada en vez de atribuir el volumen a lucia.rey'],
    kql: ['host:"mkt-wks-15" and action:("process_start" or "archive_create" or "upload")', 'details.contract:"MKT-2026-44" or details.tenant:"marketing-eu"'],
    spl: ['index=soc host=mkt-wks-15 action IN (process_start,archive_create,upload) | sort timestamp', 'index=soc details.contract=MKT-2026-44 OR details.tenant=marketing-eu'],
  }),
  makeScenario({
    id: 'mixed-alert-incident', title: 'Incidente multialerta con señales mixtas', difficulty: 'Advanced', category: 'Multi-Alert Investigation', severity: 'critical',
    description: 'PowerShell administrativo, un escaneo autorizado y actividad lateral maliciosa coinciden en la misma hora.',
    briefing: 'Agrupa alertas por causalidad, descarta coincidencias legítimas y determina el alcance real del incidente.',
    businessContext: 'Seguridad ejecuta escaneos semanales; RR. HH. despliega scripts firmados; la cuenta svc.reports no debe iniciar sesiones interactivas ni acceder a ADMIN$.',
    host: 'report-wks-02', user: 'svc.reports', sourceIp: '10.40.61.77', verdict: 'mixed', noiseCount: 218,
    noiseSources: ['windows', 'sysmon', 'endpoint', 'network', 'firewall', 'auth', 'dns', 'http'], alerts: ['PowerShell con comportamiento de administración', 'Barrido de puertos interno', 'Cuenta de servicio accede a ADMIN$', 'Salida TLS desde servidor de ficheros'],
    techniques: [technique('T1078.002'), technique('T1021.002'), technique('T1041')],
    iocs: [{ type: 'ip', value: '10.40.61.77', context: 'Estación origen de la cadena maliciosa' }, { type: 'domain', value: 'collect-cache.example', context: 'Destino sintético de salida' }],
    events: [
      e(41, 'windows', 'hr-wks-10', 'admin.hr', '10.40.6.20', '4104', 'script_block', 'success', 'Signed PowerShell script Update-HRPrinters.ps1 executed with approved ticket CHG-4830', { approved: true, signed: true, ticket: 'CHG-4830' }),
      e(45, 'firewall', 'scanner-01', 'svc.vulnscan', '10.40.5.40', 'SCAN-ALLOW', 'port_scan', 'success', 'Approved weekly vulnerability scan reached server VLAN', { approved: true, scanner_id: 'QUALYS-01' }),
      e(52, 'auth', 'dc-02', 'svc.reports', '10.40.61.77', '4768', 'ticket_request', 'success', 'Kerberos TGT for svc.reports requested from unauthorized report-wks-02', { workstation: 'report-wks-02', unauthorized: true }),
      e(54, 'sysmon', 'report-wks-02', 'svc.reports', '10.40.61.77', '1', 'process_start', 'success', 'cmd.exe spawned net.exe use \\files-02\\ADMIN$', { parent: 'cmd.exe', process: 'net.exe', unauthorized: true }),
      e(55, 'firewall', 'core-fw-01', 'svc.reports', '10.40.61.77', 'ALLOW-445', 'connection_allowed', 'success', 'SMB from report-wks-02 to files-02 allowed by service subnet rule', { destination_port: 445 }, '10.40.12.62'),
      e(56, 'windows', 'files-02', 'svc.reports', '10.40.61.77', '5145', 'share_access', 'success', 'ADMIN$ write access granted to svc.reports', { share: 'ADMIN$', unauthorized: true }),
      e(58, 'windows', 'files-02', 'SYSTEM', '10.40.61.77', '7045', 'service_create', 'success', 'Service ReportCache installed from C:\\Windows\\Temp\\rcache.exe', { service: 'ReportCache', unauthorized: true }),
      e(64, 'sysmon', 'files-02', 'SYSTEM', '10.40.12.62', '1', 'process_start', 'success', 'ReportCache service spawned tar.exe over FinanceReports', { parent: 'ReportCache.exe', process: 'tar.exe' }),
      e(68, 'dns', 'files-02', 'SYSTEM', '10.40.12.62', 'DNS-Q', 'dns_query', 'success', 'Query A collect-cache.example', { domain: 'collect-cache.example' }),
      e(70, 'http', 'proxy-02', 'SYSTEM', '10.40.12.62', 'POST-200', 'upload', 'success', 'POST 18 MB to collect-cache.example/v1/report', { domain: 'collect-cache.example', bytes: 18874368 }),
      e(74, 'endpoint', 'files-02', 'SYSTEM', '10.40.12.62', 'ISOLATE', 'host_isolate', 'success', 'files-02 isolated after unauthorized service and upload correlation', { actor: 'soc.analyst' }),
    ],
    pivot: { prompt: '¿Qué alerta es el primer pivote de la cadena maliciosa?', value: '4768 from report-wks-02', aliases: ['4768', 'Kerberos TGT'], evidenceTerms: ['4768', 'report-wks-02', 'unauthorized'] },
    scope: { prompt: '¿Qué dos hosts forman el alcance confirmado?', value: 'report-wks-02 and files-02', aliases: ['report-wks-02 y files-02', 'report-wks-02, files-02'], evidenceTerms: ['report-wks-02', 'files-02'] },
    explanation: 'PowerShell tiene firma y ticket; el escaneo procede del scanner aprobado. La cadena real empieza con un TGT no autorizado, continúa por ADMIN$, crea ReportCache y exfiltra desde files-02.',
    response: ['Aislar report-wks-02 y mantener files-02 aislado', 'Deshabilitar svc.reports y bloquear collect-cache.example'],
    remediation: ['Rotar la cuenta y revisar todos sus tickets y accesos SMB', 'Eliminar la regla amplia, recrear files-02 y evaluar FinanceReports'],
    kql: ['details.unauthorized:true or details.domain:"collect-cache.example"', 'user:"svc.reports" and host:("report-wks-02" or "files-02")'],
    spl: ['index=soc details.unauthorized=true OR details.domain=collect-cache.example | sort timestamp', 'index=soc user=svc.reports host IN (report-wks-02,files-02) | transaction user maxspan=30m'],
    sigmaSelection: 'eventCode: 7045\n    details.service: ReportCache',
  }),
];
